version: "3.8"
services:
  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_DB: "coincoin"
      POSTGRES_USER: "coincoin"
      POSTGRES_PASSWORD: "coincoin"
    networks:
      - database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres17:
    image: "postgres:17"
    environment:
      POSTGRES_DB: "coincoin"
      POSTGRES_USER: "coincoin"
      POSTGRES_PASSWORD: "coincoin"
    networks:
      - database
    volumes:
      - postgres17_data:/var/lib/postgresql/data

  redis:
    image: "redis"
    networks:
      - database

  coincoin:
    image: "killruana/coincoin:main"
    environment:
        DATABASE_URL: "postgres://coincoin:coincoin@postgres/coincoin"
        CELERY_BROKER_URL: "redis://redis/0"
        SECRET_KEY_FILE: /run/secrets/coincoin_secret_key
        ALLOWED_HOSTS: coincoin.jtremesay.org
    ports:
      - "8001:8001"
    networks:
      - database
      - traefik_public
    secrets:
      - coincoin_secret_key
    labels:
      - traefik.enable=true
      - traefik.http.routers.coincoin.rule=Host(`coincoin.jtremesay.org`) || Host(`coincoin.slaanesh.org`)
      - traefik.http.routers.coincoin.entrypoints=websecure
      - traefik.http.services.coincoin.loadbalancer.server.port=8001
      - traefik.http.routers.coincoin.service=coincoin
      - traefik.http.routers.coincoin.tls.certresolver=leresolver
    deploy:
      labels:
        - shepherd.autodeploy=false

  celery_beat:
    image: "killruana/coincoin:main"
    command: "celery -A proj beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    environment:
        DATABASE_URL: "postgres://coincoin:coincoin@postgres/coincoin"
        CELERY_BROKER_URL: "redis://redis/0"
        SECRET_KEY_FILE: /run/secrets/coincoin_secret_key
        ALLOWED_HOSTS: coincoin.jtremesay.org
    networks:
      - database
    secrets:
      - coincoin_secret_key
    deploy:
      labels:
        - shepherd.autodeploy=false

  celery_worker:
    image: "killruana/coincoin:main"
    command: "celery -A proj worker -l INFO"
    environment:
        DATABASE_URL: "postgres://coincoin:coincoin@postgres/coincoin"
        CELERY_BROKER_URL: "redis://redis/0"
        SECRET_KEY_FILE: /run/secrets/coincoin_secret_key
        ALLOWED_HOSTS: coincoin.jtremesay.org
    networks:
      - database
    secrets:
      - coincoin_secret_key
    deploy:
      labels:
        - shepherd.autodeploy=false

networks:
  database:
  traefik_public:
    external: true

secrets:
  coincoin_secret_key:
    external: true

volumes:
  postgres_data:
  postgres17_data:
