# Generated by Django 4.2 on 2023-05-02 21:11

import uuid

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name"
                    ),
                ),
                ("url", models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField()),
                ("info", models.CharField(max_length=256)),
                ("message", models.TextField()),
                ("login", models.CharField(max_length=32)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_set",
                        to="coincoin.board",
                    ),
                ),
            ],
            options={
                "unique_together": {("board", "id")},
            },
        ),
    ]
