# Generated by Django 4.2 on 2023-05-02 21:12

from django.db import migrations


def add_linuxfr(apps, schema_editor):
    Board = apps.get_model("coincoin", "Board")
    Board.objects.create(
        uuid="3cbc9b13-8560-4feb-b0b5-79207d36dc52",
        name="LinuxFR",
        url="https://linuxfr.org/board/index.xml",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("coincoin", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_linuxfr),
    ]
