# Generated by Django 4.2.1 on 2023-05-08 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coincoin", "0002_add_linuxfr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="url",
            new_name="backend_url",
        ),
    ]
